name: sodeci_mobile
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_html: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Rxdart
  rxdart: ^0.22.2

  #Font Awesome icon
  font_awesome_flutter: ^8.5.0

  #Use for sharePrefs
  shared_preferences: ^0.5.4+6

  #Toast
  fluttertoast: ^3.1.3

  #Pull to refresh
  pull_to_refresh: ^1.5.6

  #For date parse
  intl: ^0.16.0

  #For make request
  http: ^0.12.0+2

  #For upload image
  dio: 3.0.7

  #For image picker
  image_picker: ^0.6.1

  #For webview
  webview_flutter: ^0.3.15+1

  #For location change
  location: ^2.3.5

  #For skeletton anime
  skeleton_text: ^1.0.0

  #For SVG
  flutter_svg: ^0.14.3


  #For make call, open url etc
  url_launcher: ^5.1.0

  #For lat long cal
  latlong: ^0.6.1

  #For pdf view
  photo_view: ^0.7.0

  #For file info
  path: ^1.6.4

  #For  chart
  charts_flutter: ^0.8.1

  #For transparent image
  transparent_image: ^1.0.0

  #For hide flutter red screen
  catcher: ^0.2.3

  #For file chooser
  file_picker: ^1.4.3+1


  #For check internet connexion
  connectivity: ^0.4.6

  #For toast
  #toast: ^0.1.5

  #For html unsecap



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/PAGE_ACCUEIL/
    - assets/images/INFOS_UTILES/
    - assets/images/CONTRAT/infos/
    - assets/images/CONTACTS/
    - assets/images/CONSOMMATION/
    - assets/images/SIGNALER_UN_INCIDENT/
    - assets/images/RESEAUX_DAGENCES/
    - assets/images/ESPACE_PERSONNEL/Bienvenue/
    - assets/images/ESPACE_PERSONNEL/Reclamations/
    - assets/images/ESPACE_PERSONNEL/Demandes/
    - assets/images/
    - assets/images/Compteur3D/
    - assets/image_service.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Myriad
       fonts:
         - asset: fonts/MYRIADPRO_REGULAR.OTF
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
